import { describe, expect, it } from 'vitest';
import {
  buildCircuitDiagram,
  simulateCircuit,
  toDiagramSvg,
  toKiCadNetlist,
  toSpice,
  validateCircuit,
} from './pcbGenerator.js';

const aiCircuit = {
  title: 'AI generated test circuit',
  type: 'ai_generated',
  supplyVoltage: 5,
  components: [
    { ref: 'V1', kind: 'voltage_source', value: '5V', nodes: ['VIN', '0'] },
    { ref: 'R1', kind: 'resistor', value: '1k', nodes: ['VIN', 'VOUT'] },
    { ref: 'C1', kind: 'capacitor', value: '100nF', nodes: ['VOUT', '0'] },
  ],
  notes: ['Generated by the AI provider.'],
};

const netMembershipFromDiagram = (diagram) =>
  new Map(
    diagram.nets.map((net) => [
      net.name,
      net.connections.map((connection) => `${connection.ref}:${connection.pin}`).sort(),
    ]),
  );

const netMembershipFromKiCad = (netlist) => {
  const memberships = new Map();
  const netPattern = /<net[^>]*name="([^"]+)"[^>]*>([\s\S]*?)<\/net>/g;
  for (const match of netlist.matchAll(netPattern)) {
    const nodes = [...match[2].matchAll(/<node ref="([^"]+)" pin="([^"]+)" \/>/g)]
      .map((nodeMatch) => `${nodeMatch[1]}:${nodeMatch[2]}`)
      .sort();
    memberships.set(match[1], nodes);
  }
  return memberships;
};

describe('prompt-to-pcb generator', () => {
  it('validates an AI-provided circuit model', () => {
    const validation = validateCircuit(aiCircuit);

    expect(validation.ok).toBe(true);
    expect(validation.errors).toEqual([]);
  });

  it('exports an AI-provided circuit to SPICE and KiCad netlist formats', () => {
    const spice = toSpice(aiCircuit);
    const kicadNetlist = toKiCadNetlist(aiCircuit);

    expect(spice).toContain('R1 VIN VOUT 1k');
    expect(spice).toContain('C1 VOUT 0 100n');
    expect(kicadNetlist).toContain('<comp ref="R1">');
    expect(kicadNetlist).toContain('<net');
  });

  it('normalizes AI refs to SPICE-safe prefixes during export', () => {
    const spice = toSpice({
      title: 'LED ref safety',
      type: 'ai_generated',
      supplyVoltage: 5,
      components: [
        { ref: 'V1', kind: 'voltage_source', value: '5V', nodes: ['VIN', '0'] },
        { ref: 'LED1', kind: 'led', value: 'red', nodes: ['VIN', '0'] },
        { ref: 'LOAD1', kind: 'load', value: '1k', nodes: ['VIN', '0'] },
      ],
      notes: [],
    });

    expect(spice).toContain('D_LED1 VIN 0 DRED');
    expect(spice).toContain('R_LOAD1 VIN 0 1k');
  });

  it('returns generic simulation metadata for AI-generated circuits', () => {
    const simulation = simulateCircuit(aiCircuit);

    expect(simulation.engine).toBe('AI-generated Ngspice-ready export');
    expect(simulation.metrics).toContainEqual({ label: 'Components', value: '3' });
    expect(simulation.command).toBe('ngspice generated.cir');
  });

  it('reports floating nodes during validation', () => {
    const validation = validateCircuit({
      title: 'Bad circuit',
      type: 'custom',
      supplyVoltage: 5,
      components: [{ ref: 'R1', kind: 'resistor', value: '1k', nodes: ['A', '0'] }],
    });

    expect(validation.ok).toBe(true);
    expect(validation.warnings).toContain('A only connects to one pin and may be floating.');
  });

  it('builds a readable schematic diagram model for an RC filter', () => {
    const diagram = buildCircuitDiagram(aiCircuit);

    expect(diagram.components).toHaveLength(3);
    expect(diagram.components.find((part) => part.ref === 'R1')).toMatchObject({
      symbolType: 'resistor',
      nodes: ['VIN', 'VOUT'],
    });
    expect(diagram.components.find((part) => part.ref === 'C1')).toMatchObject({
      symbolType: 'capacitor',
      nodes: ['VOUT', '0'],
    });
    expect(diagram.nets.map((net) => net.name)).toEqual(expect.arrayContaining(['VIN', 'VOUT', '0']));
    expect(diagram.wires).toHaveLength(6);
  });

  it('places voltage divider output and load connections in the diagram model', () => {
    const circuit = {
      title: 'Voltage divider',
      type: 'voltage_divider',
      supplyVoltage: 12,
      components: [
        { ref: 'V1', kind: 'voltage_source', value: '12V', nodes: ['VCC', '0'] },
        { ref: 'R1', kind: 'resistor', value: '7.5k', nodes: ['VCC', 'OUT'] },
        { ref: 'R2', kind: 'resistor', value: '2.7k', nodes: ['OUT', '0'] },
        { ref: 'RLOAD', kind: 'load', value: '10k', nodes: ['OUT', '0'] },
      ],
      notes: [],
    };
    const diagram = buildCircuitDiagram(circuit);

    expect(diagram.nets.find((net) => net.name === 'OUT').connections).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ ref: 'R1', pin: 2 }),
        expect.objectContaining({ ref: 'R2', pin: 1 }),
        expect.objectContaining({ ref: 'RLOAD', pin: 1 }),
      ]),
    );
    expect(diagram.components.find((part) => part.ref === 'RLOAD').symbolType).toBe('resistor');
  });

  it('keeps LED and transistor circuit connectivity in schematic symbols', () => {
    const circuit = {
      title: 'NPN LED switch',
      type: 'switch',
      supplyVoltage: 5,
      components: [
        { ref: 'V1', kind: 'voltage_source', value: '5V', nodes: ['VIN', '0'] },
        { ref: 'RLED', kind: 'resistor', value: '330', nodes: ['VIN', 'LED_ANODE'] },
        { ref: 'DLED1', kind: 'led', value: 'red', nodes: ['LED_ANODE', 'COLLECTOR'] },
        { ref: 'Q1', kind: 'bjt_npn', value: '2N2222', nodes: ['COLLECTOR', 'BASE', '0'] },
      ],
      notes: [],
    };
    const diagram = buildCircuitDiagram(circuit);

    expect(diagram.components.find((part) => part.ref === 'DLED1').symbolType).toBe('led');
    expect(diagram.components.find((part) => part.ref === 'Q1').symbolType).toBe('bjt_npn');
    expect(diagram.nets.find((net) => net.name === 'COLLECTOR').connections).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ ref: 'DLED1', pin: 2 }),
        expect.objectContaining({ ref: 'Q1', pin: 1 }),
      ]),
    );
  });

  it('renders op amps with schematic pin roles and preserves SPICE order', () => {
    const circuit = {
      title: 'Op amp buffer',
      type: 'opamp',
      supplyVoltage: 12,
      components: [
        { ref: 'XU1', kind: 'opamp', value: 'LM358', nodes: ['VINP', 'VINN', 'VOUT', 'VCC', '0'] },
        { ref: 'V1', kind: 'voltage_source', value: '12V', nodes: ['VCC', '0'] },
      ],
      notes: [],
    };
    const diagram = buildCircuitDiagram(circuit);
    const opamp = diagram.components.find((part) => part.ref === 'XU1');
    const pins = new Map(opamp.pins.map((pin) => [pin.pinIndex, pin]));

    expect(opamp).toMatchObject({ symbolType: 'opamp', width: 150, height: 110 });
    expect(pins.get(1)).toMatchObject({ node: 'VINP' });
    expect(pins.get(1).x).toBeLessThan(opamp.x);
    expect(pins.get(1).y).toBeGreaterThan(opamp.y);
    expect(pins.get(2)).toMatchObject({ node: 'VINN' });
    expect(pins.get(2).x).toBeLessThan(opamp.x);
    expect(pins.get(2).y).toBeLessThan(opamp.y);
    expect(pins.get(3)).toMatchObject({ node: 'VOUT' });
    expect(pins.get(3).x).toBeGreaterThan(opamp.x);
    expect(pins.get(4)).toMatchObject({ node: 'VCC' });
    expect(pins.get(4).y).toBeLessThan(opamp.y);
    expect(pins.get(5)).toMatchObject({ node: '0' });
    expect(pins.get(5).y).toBeGreaterThan(opamp.y);
    expect(toSpice(circuit)).toContain('XU1 VINP VINN VOUT VCC 0 LM358');
  });

  it('exports op amp triangle labels in the diagram SVG', () => {
    const svg = toDiagramSvg(buildCircuitDiagram({
      title: 'Op amp SVG',
      type: 'opamp',
      supplyVoltage: 12,
      components: [
        { ref: 'XU1', kind: 'opamp', value: 'LM358', nodes: ['VINP', 'VINN', 'VOUT', 'VCC', '0'] },
        { ref: 'V1', kind: 'voltage_source', value: '12V', nodes: ['VCC', '0'] },
      ],
      notes: [],
    }));

    expect(svg).toContain('<polygon class="diagram-fill"');
    expect(svg).toContain('>+</text>');
    expect(svg).toContain('>-</text>');
    expect(svg).toContain('>V+</text>');
    expect(svg).toContain('>V-</text>');
  });

  it('warns when an op amp is missing schematic role nodes', () => {
    const validation = validateCircuit({
      title: 'Incomplete op amp',
      type: 'opamp',
      supplyVoltage: 5,
      components: [
        { ref: 'XU1', kind: 'opamp', value: 'LM358', nodes: ['VINP', 'VINN', 'VOUT'] },
        { ref: 'V1', kind: 'voltage_source', value: '5V', nodes: ['VCC', '0'] },
      ],
      notes: [],
    });

    expect(validation.ok).toBe(true);
    expect(validation.warnings).toContain('XU1 op amp should include + input, - input, output, V+, and V- nodes.');
  });

  it('keeps diagram net memberships consistent with the KiCad netlist', () => {
    const diagramMembership = netMembershipFromDiagram(buildCircuitDiagram(aiCircuit));
    const kicadMembership = netMembershipFromKiCad(toKiCadNetlist(aiCircuit));

    expect([...diagramMembership.keys()].sort()).toEqual([...kicadMembership.keys()].sort());
    for (const [net, connections] of kicadMembership.entries()) {
      expect(diagramMembership.get(net)).toEqual(connections);
    }
  });

  it('exports the generated diagram model as SVG', () => {
    const svg = toDiagramSvg(buildCircuitDiagram(aiCircuit));

    expect(svg).toContain('<svg');
    expect(svg).toContain('R1');
    expect(svg).toContain('VOUT');
  });
});
