import { describe, expect, it } from 'vitest';
import { simulateCircuit, toKiCadNetlist, toSpice, validateCircuit } from './pcbGenerator.js';

const aiCircuit = {
  title: 'AI generated test circuit',
  type: 'ai_generated',
  supplyVoltage: 5,
  components: [
    { ref: 'V1', kind: 'voltage_source', value: '5V', nodes: ['VIN', '0'] },
    { ref: 'R1', kind: 'resistor', value: '1k', nodes: ['VIN', 'VOUT'] },
    { ref: 'C1', kind: 'capacitor', value: '100nF', nodes: ['VOUT', '0'] },
  ],
  notes: ['Generated by the AI provider.'],
};

describe('prompt-to-pcb generator', () => {
  it('validates an AI-provided circuit model', () => {
    const validation = validateCircuit(aiCircuit);

    expect(validation.ok).toBe(true);
    expect(validation.errors).toEqual([]);
  });

  it('exports an AI-provided circuit to SPICE and KiCad netlist formats', () => {
    const spice = toSpice(aiCircuit);
    const kicadNetlist = toKiCadNetlist(aiCircuit);

    expect(spice).toContain('R1 VIN VOUT 1k');
    expect(spice).toContain('C1 VOUT 0 100n');
    expect(kicadNetlist).toContain('<comp ref="R1">');
    expect(kicadNetlist).toContain('<net');
  });

  it('normalizes AI refs to SPICE-safe prefixes during export', () => {
    const spice = toSpice({
      title: 'LED ref safety',
      type: 'ai_generated',
      supplyVoltage: 5,
      components: [
        { ref: 'V1', kind: 'voltage_source', value: '5V', nodes: ['VIN', '0'] },
        { ref: 'LED1', kind: 'led', value: 'red', nodes: ['VIN', '0'] },
        { ref: 'LOAD1', kind: 'load', value: '1k', nodes: ['VIN', '0'] },
      ],
      notes: [],
    });

    expect(spice).toContain('D_LED1 VIN 0 DRED');
    expect(spice).toContain('R_LOAD1 VIN 0 1k');
  });

  it('returns generic simulation metadata for AI-generated circuits', () => {
    const simulation = simulateCircuit(aiCircuit);

    expect(simulation.engine).toBe('AI-generated Ngspice-ready export');
    expect(simulation.metrics).toContainEqual({ label: 'Components', value: '3' });
    expect(simulation.command).toBe('ngspice generated.cir');
  });

  it('reports floating nodes during validation', () => {
    const validation = validateCircuit({
      title: 'Bad circuit',
      type: 'custom',
      supplyVoltage: 5,
      components: [{ ref: 'R1', kind: 'resistor', value: '1k', nodes: ['A', '0'] }],
    });

    expect(validation.ok).toBe(true);
    expect(validation.warnings).toContain('A only connects to one pin and may be floating.');
  });
});
