export const validateCircuit = (circuit) => {
  const errors = [];
  const warnings = [];
  const nodeUse = new Map();

  for (const part of circuit.components) {
    if (!part.value) errors.push(`${part.ref} is missing a value.`);
    if (!part.nodes.includes('0') && part.kind === 'voltage_source') {
      warnings.push(`${part.ref} does not reference ground.`);
    }
    part.nodes.forEach((node) => nodeUse.set(node, (nodeUse.get(node) ?? 0) + 1));
  }

  if (!nodeUse.has('0')) errors.push('No ground node was generated.');
  for (const [node, count] of nodeUse.entries()) {
    if (node !== '0' && count < 2) warnings.push(`${node} only connects to one pin and may be floating.`);
  }

  if (!circuit.supplyVoltage || circuit.supplyVoltage <= 0) errors.push('Supply voltage must be positive.');
  if (circuit.supplyVoltage > 60) warnings.push('Supply voltage is high for beginner/maker breadboard circuits.');

  return { ok: errors.length === 0, errors, warnings };
};

const sanitizeSpiceRef = (ref) => String(ref || 'X').replace(/[^a-z0-9_]/gi, '_').toUpperCase();

const spiceRef = (part) => {
  const base = sanitizeSpiceRef(part.ref);
  const prefixByKind = {
    voltage_source: 'V',
    signal_source: 'V',
    resistor: 'R',
    load: 'R',
    capacitor: 'C',
    inductor: 'L',
    diode: 'D',
    led: 'D',
    bjt_npn: 'Q',
    bjt_pnp: 'Q',
    mosfet_n: 'M',
    mosfet_p: 'M',
    opamp: 'X',
    regulator: 'V',
  };
  const prefix = prefixByKind[part.kind] || 'X';
  return base.startsWith(prefix) ? base : `${prefix}_${base}`;
};

const cleanVoltageValue = (value) => String(value || '0').replace(/v$/i, '');

const regulatorVoltage = (value) => {
  const text = String(value || '').toLowerCase();
  if (text.includes('7805')) return '5';
  if (text.includes('7812')) return '12';
  if (text.includes('7905')) return '-5';
  return cleanVoltageValue(text).match(/\d+(?:\.\d+)?/)?.[0] || '5';
};

const regulatorOutputNode = (nodes = []) => {
  const namedOutput = nodes.find((node) => /^v?out/i.test(node));
  return namedOutput || nodes.at(-1) || 'VOUT';
};

export const toSpice = (circuit) => {
  const lines = [`* ${circuit.title}`, '* Generated by Prompt-to-PCB Generator'];
  for (const part of circuit.components) {
    const [a, b, c, d, e] = part.nodes;
    const ref = spiceRef(part);
    if (part.kind === 'voltage_source') lines.push(`${ref} ${a} ${b} DC ${cleanVoltageValue(part.value)}`);
    if (part.kind === 'signal_source') lines.push(`${ref} ${a} ${b} ${part.value}`);
    if (part.kind === 'resistor' || part.kind === 'load') lines.push(`${ref} ${a} ${b} ${part.value}`);
    if (part.kind === 'capacitor') lines.push(`${ref} ${a} ${b} ${part.value.replace(/f$/i, '')}`);
    if (part.kind === 'inductor') lines.push(`${ref} ${a} ${b} ${part.value.replace(/h$/i, '')}`);
    if (part.kind === 'diode') lines.push(`${ref} ${a} ${b} DGEN`);
    if (part.kind === 'led') lines.push(`${ref} ${a} ${b} DRED`);
    if (part.kind === 'bjt_npn') lines.push(`${ref} ${a} ${b} ${c} Q2N2222`);
    if (part.kind === 'opamp') lines.push(`${ref} ${a} ${b} ${c} ${d} ${e} LM358`);
    if (part.kind === 'regulator') lines.push(`${ref} ${regulatorOutputNode(part.nodes)} 0 DC ${regulatorVoltage(part.value)}`);
  }
  lines.push('.model DGEN D(IS=1e-14 RS=1 N=1)');
  lines.push('.model DRED D(IS=1e-20 N=2 RS=10 CJO=2p BV=5 IBV=10u)');
  lines.push('.model Q2N2222 NPN(IS=1e-14 BF=200 VAF=100)');
  lines.push('.tran 0.1ms 20ms');
  lines.push('.op');
  lines.push('.end');
  return lines.join('\n');
};

export const toKiCadNetlist = (circuit) => {
  const nets = [...new Set(circuit.components.flatMap((part) => part.nodes))];
  const compXml = circuit.components
    .map(
      (part) => `    <comp ref="${part.ref}">
      <value>${part.value}</value>
      <footprint>${part.footprint}</footprint>
      <fields>
        <field name="Kind">${part.kind}</field>
      </fields>
    </comp>`,
    )
    .join('\n');
  const netXml = nets
    .map((net, index) => {
      const nodes = circuit.components
        .flatMap((part) =>
          part.nodes
            .map((node, pinIndex) => ({ node, pinIndex: pinIndex + 1, ref: part.ref }))
            .filter((pin) => pin.node === net),
        )
        .map((pin) => `      <node ref="${pin.ref}" pin="${pin.pinIndex}" />`)
        .join('\n');
      return `    <net code="${index}" name="${net}">
${nodes}
    </net>`;
    })
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<export version="D">
  <design>
    <source>prompt-to-pcb-generator</source>
    <date>${new Date().toISOString()}</date>
    <tool>Prompt-to-PCB Generator MVP</tool>
  </design>
  <components>
${compXml}
  </components>
  <nets>
${netXml}
  </nets>
</export>`;
};

export const simulateCircuit = (circuit) => {
  return {
    engine: 'AI-generated Ngspice-ready export',
    status: 'ready',
    metrics: [
      { label: 'Components', value: String(circuit.components.length) },
      { label: 'Nets', value: String(new Set(circuit.components.flatMap((part) => part.nodes)).size) },
      { label: 'Analysis', value: 'SPICE deck generated' },
    ],
    command: 'ngspice generated.cir',
  };
};
