import { describe, expect, it } from 'vitest';
import {
  buildCircuitDiagram,
  diagramComponentsOverlap,
  layoutCircuitDiagram,
  simulateCircuit,
  toDiagramSvg,
  toKiCadNetlist,
  routeDiagramWire,
  toSpice,
  validateCircuit,
} from './pcbGenerator.js';

const aiCircuit = {
  title: 'AI generated test circuit',
  type: 'ai_generated',
  supplyVoltage: 5,
  components: [
    { ref: 'V1', kind: 'voltage_source', value: '5V', nodes: ['VIN', '0'] },
    { ref: 'R1', kind: 'resistor', value: '1k', nodes: ['VIN', 'VOUT'] },
    { ref: 'C1', kind: 'capacitor', value: '100nF', nodes: ['VOUT', '0'] },
  ],
  notes: ['Generated by the AI provider.'],
};

const differenceAmplifier = {
  title: 'Difference Amplifier',
  type: 'amplifier',
  supplyVoltage: 5,
  components: [
    { ref: 'V1', kind: 'voltage_source', value: '5V', nodes: ['VCC', '0'] },
    { ref: 'V2', kind: 'voltage_source', value: '2.5V', nodes: ['VBIAS', '0'] },
    { ref: 'R1', kind: 'resistor', value: '10k', nodes: ['VINP', 'OPP'] },
    { ref: 'R2', kind: 'resistor', value: '10k', nodes: ['OPP', 'VBIAS'] },
    { ref: 'R3', kind: 'resistor', value: '10k', nodes: ['VINN', 'OPN'] },
    { ref: 'R4', kind: 'resistor', value: '10k', nodes: ['OPN', 'VBIAS'] },
    { ref: 'XU1', kind: 'opamp', value: 'LM358', nodes: ['OPP', 'OPN', 'VOUT', 'VCC', '0'] },
    { ref: 'RLOAD', kind: 'load', value: '10k', nodes: ['VOUT', '0'] },
  ],
  notes: [],
};

const netMembershipFromDiagram = (diagram) =>
  new Map(
    diagram.nets.map((net) => [
      net.name,
      net.connections.map((connection) => `${connection.ref}:${connection.pin}`).sort(),
    ]),
  );

const netMembershipFromKiCad = (netlist) => {
  const memberships = new Map();
  const netPattern = /<net[^>]*name="([^"]+)"[^>]*>([\s\S]*?)<\/net>/g;
  for (const match of netlist.matchAll(netPattern)) {
    const nodes = [...match[2].matchAll(/<node ref="([^"]+)" pin="([^"]+)" \/>/g)]
      .map((nodeMatch) => `${nodeMatch[1]}:${nodeMatch[2]}`)
      .sort();
    memberships.set(match[1], nodes);
  }
  return memberships;
};

const testPathSegments = (points) => points.slice(1).map((point, index) => ({ from: points[index], to: point }));
const testPointOnSegment = (point, segment) => (
  segment.from.x === segment.to.x
    ? point.x === segment.from.x
      && point.y >= Math.min(segment.from.y, segment.to.y)
      && point.y <= Math.max(segment.from.y, segment.to.y)
    : point.y === segment.from.y
      && point.x >= Math.min(segment.from.x, segment.to.x)
      && point.x <= Math.max(segment.from.x, segment.to.x)
);
const testSegmentsTouch = (first, second) =>
  [first.from, first.to].some((point) => testPointOnSegment(point, second))
  || [second.from, second.to].some((point) => testPointOnSegment(point, first));

const expectNodePhysicallyConnected = (diagram, node) => {
  const wires = diagram.wires.filter((wire) => wire.node === node);
  expect(wires.length).toBeGreaterThan(1);
  const visited = new Set([wires[0].id]);
  let changed = true;
  while (changed) {
    changed = false;
    for (const wire of wires) {
      if (visited.has(wire.id)) continue;
      const touchesVisited = wires
        .filter((other) => visited.has(other.id))
        .some((other) => testPathSegments(wire.points).some((segment) =>
          testPathSegments(other.points).some((otherSegment) => testSegmentsTouch(segment, otherSegment))));
      if (touchesVisited) {
        visited.add(wire.id);
        changed = true;
      }
    }
  }
  expect(visited.size).toBe(wires.length);
};

describe('prompt-to-pcb generator', () => {
  it('validates an AI-provided circuit model', () => {
    const validation = validateCircuit(aiCircuit);

    expect(validation.ok).toBe(true);
    expect(validation.errors).toEqual([]);
  });

  it('exports an AI-provided circuit to SPICE and KiCad netlist formats', () => {
    const spice = toSpice(aiCircuit);
    const kicadNetlist = toKiCadNetlist(aiCircuit);

    expect(spice).toContain('R1 VIN VOUT 1k');
    expect(spice).toContain('C1 VOUT 0 100n');
    expect(kicadNetlist).toContain('<comp ref="R1">');
    expect(kicadNetlist).toContain('<net');
  });

  it('renders node zero as a standard ground symbol in exported SVG', () => {
    const svg = toDiagramSvg(buildCircuitDiagram(aiCircuit));

    expect(svg).toContain('class="diagram-ground"');
    expect(svg).toContain('aria-label="Ground"');
    expect(svg).not.toContain('>0</text>');
  });

  it('normalizes AI refs to SPICE-safe prefixes during export', () => {
    const spice = toSpice({
      title: 'LED ref safety',
      type: 'ai_generated',
      supplyVoltage: 5,
      components: [
        { ref: 'V1', kind: 'voltage_source', value: '5V', nodes: ['VIN', '0'] },
        { ref: 'LED1', kind: 'led', value: 'red', nodes: ['VIN', '0'] },
        { ref: 'LOAD1', kind: 'load', value: '1k', nodes: ['VIN', '0'] },
      ],
      notes: [],
    });

    expect(spice).toContain('D_LED1 VIN 0 DRED');
    expect(spice).toContain('R_LOAD1 VIN 0 1k');
  });

  it('returns generic simulation metadata for AI-generated circuits', () => {
    const simulation = simulateCircuit(aiCircuit);

    expect(simulation.engine).toBe('AI-generated Ngspice-ready export');
    expect(simulation.metrics).toContainEqual({ label: 'Components', value: '3' });
    expect(simulation.command).toBe('ngspice generated.cir');
  });

  it('reports floating nodes during validation', () => {
    const validation = validateCircuit({
      title: 'Bad circuit',
      type: 'custom',
      supplyVoltage: 5,
      components: [{ ref: 'R1', kind: 'resistor', value: '1k', nodes: ['A', '0'] }],
    });

    expect(validation.ok).toBe(true);
    expect(validation.warnings).toContain('A only connects to one pin and may be floating.');
  });

  it('does not warn for intentional external terminal nodes', () => {
    const validation = validateCircuit({
      title: 'External input',
      type: 'custom',
      supplyVoltage: 5,
      components: [{ ref: 'R1', kind: 'resistor', value: '1k', nodes: ['VIN', '0'] }],
      schematic: {
        version: 1,
        externalTerminals: [{ net: 'VIN', label: 'VIN', type: 'input', side: 'left' }],
      },
    });

    expect(validation.ok).toBe(true);
    expect(validation.warnings).not.toContain('VIN only connects to one pin and may be floating.');
  });

  it('builds a readable schematic diagram model for an RC filter', () => {
    const diagram = buildCircuitDiagram(aiCircuit);

    expect(diagram.components).toHaveLength(3);
    expect(diagram.components.find((part) => part.ref === 'R1')).toMatchObject({
      symbolType: 'resistor',
      nodes: ['VIN', 'VOUT'],
    });
    expect(diagram.components.find((part) => part.ref === 'C1')).toMatchObject({
      symbolType: 'capacitor',
      nodes: ['VOUT', '0'],
    });
    expect(diagram.nets.map((net) => net.name)).toEqual(expect.arrayContaining(['VIN', 'VOUT', '0']));
    expect(diagram.wires).toHaveLength(6);
    for (const [index, component] of diagram.components.entries()) {
      expect(diagram.components.slice(index + 1).some((other) =>
        diagramComponentsOverlap(component, other))).toBe(false);
    }
  });

  it('separates crowded generated components with minimum clearance', () => {
    const crowded = {
      title: 'Crowded loads',
      type: 'custom',
      supplyVoltage: 5,
      components: [
        { ref: 'V1', kind: 'voltage_source', value: '5V', nodes: ['VCC', '0'] },
        { ref: 'R1', kind: 'load', value: '1k', nodes: ['OUT', '0'] },
        { ref: 'R2', kind: 'load', value: '2k', nodes: ['OUT', '0'] },
        { ref: 'R3', kind: 'load', value: '3k', nodes: ['OUT', '0'] },
      ],
      notes: [],
    };
    const diagram = buildCircuitDiagram(crowded);

    for (const [index, component] of diagram.components.entries()) {
      expect(diagram.components.slice(index + 1).some((other) =>
        diagramComponentsOverlap(component, other))).toBe(false);
    }
    // Slot placement gives each of the four parts its own slot in the fixed grid.
    expect(diagram.slotLayout).toEqual({ rows: 2, cols: 4 });
  });

  it('places voltage divider output and load connections in the diagram model', () => {
    const circuit = {
      title: 'Voltage divider',
      type: 'voltage_divider',
      supplyVoltage: 12,
      components: [
        { ref: 'V1', kind: 'voltage_source', value: '12V', nodes: ['VCC', '0'] },
        { ref: 'R1', kind: 'resistor', value: '7.5k', nodes: ['VCC', 'OUT'] },
        { ref: 'R2', kind: 'resistor', value: '2.7k', nodes: ['OUT', '0'] },
        { ref: 'RLOAD', kind: 'load', value: '10k', nodes: ['OUT', '0'] },
      ],
      notes: [],
    };
    const diagram = buildCircuitDiagram(circuit);

    expect(diagram.nets.find((net) => net.name === 'OUT').connections).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ ref: 'R1', pin: 2 }),
        expect.objectContaining({ ref: 'R2', pin: 1 }),
        expect.objectContaining({ ref: 'RLOAD', pin: 1 }),
      ]),
    );
    expect(diagram.components.find((part) => part.ref === 'RLOAD').symbolType).toBe('resistor');
  });

  it('keeps LED and transistor circuit connectivity in schematic symbols', () => {
    const circuit = {
      title: 'NPN LED switch',
      type: 'switch',
      supplyVoltage: 5,
      components: [
        { ref: 'V1', kind: 'voltage_source', value: '5V', nodes: ['VIN', '0'] },
        { ref: 'RLED', kind: 'resistor', value: '330', nodes: ['VIN', 'LED_ANODE'] },
        { ref: 'DLED1', kind: 'led', value: 'red', nodes: ['LED_ANODE', 'COLLECTOR'] },
        { ref: 'Q1', kind: 'bjt_npn', value: '2N2222', nodes: ['COLLECTOR', 'BASE', '0'] },
      ],
      notes: [],
    };
    const diagram = buildCircuitDiagram(circuit);

    expect(diagram.components.find((part) => part.ref === 'DLED1').symbolType).toBe('led');
    expect(diagram.components.find((part) => part.ref === 'Q1').symbolType).toBe('bjt_npn');
    expect(diagram.nets.find((net) => net.name === 'COLLECTOR').connections).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ ref: 'DLED1', pin: 2 }),
        expect.objectContaining({ ref: 'Q1', pin: 1 }),
      ]),
    );
  });

  it('renders op amps with schematic pin roles and preserves SPICE order', () => {
    const circuit = {
      title: 'Op amp buffer',
      type: 'opamp',
      supplyVoltage: 12,
      components: [
        { ref: 'XU1', kind: 'opamp', value: 'LM358', nodes: ['VINP', 'VINN', 'VOUT', 'VCC', '0'] },
        { ref: 'V1', kind: 'voltage_source', value: '12V', nodes: ['VCC', '0'] },
      ],
      notes: [],
    };
    const diagram = buildCircuitDiagram(circuit);
    const opamp = diagram.components.find((part) => part.ref === 'XU1');
    const pins = new Map(opamp.pins.map((pin) => [pin.pinIndex, pin]));

    expect(opamp).toMatchObject({ symbolType: 'opamp', width: 150, height: 110 });
    expect(pins.get(1)).toMatchObject({ node: 'VINP' });
    expect(pins.get(1).x).toBeLessThan(opamp.x);
    expect(pins.get(1).y).toBeGreaterThan(opamp.y);
    expect(pins.get(2)).toMatchObject({ node: 'VINN' });
    expect(pins.get(2).x).toBeLessThan(opamp.x);
    expect(pins.get(2).y).toBeLessThan(opamp.y);
    expect(pins.get(3)).toMatchObject({ node: 'VOUT' });
    expect(pins.get(3).x).toBeGreaterThan(opamp.x);
    expect(pins.get(4)).toMatchObject({ node: 'VCC' });
    expect(pins.get(4).y).toBeLessThan(opamp.y);
    expect(pins.get(5)).toMatchObject({ node: '0' });
    expect(pins.get(5).y).toBeGreaterThan(opamp.y);
    const spice = toSpice(circuit);
    expect(spice).toContain('XU1 VINP VINN VOUT VCC 0 LM358');
    expect(spice).toContain('.subckt LM358 INP INN OUT VCC VEE');
    expect(spice).toContain('.ends LM358');
  });

  it('routes automatic wires around unrelated component bodies', () => {
    const diagram = {
      components: [
        { ref: 'XU1', x: 400, y: 300, width: 150, height: 110, pins: [{ pinIndex: 3, x: 475, y: 300 }] },
        { ref: 'R1', x: 475, y: 120, width: 110, height: 58, pins: [] },
      ],
      nets: [{ name: 'OUT', x: 650, y: 120 }],
    };
    const points = routeDiagramWire(diagram, { ref: 'XU1', pin: 3, node: 'OUT' });

    expect(points).toEqual([
      { x: 475, y: 300 },
      { x: 650, y: 300 },
      { x: 650, y: 120 },
    ]);
  });

  it('exports op amp triangle labels in the diagram SVG', () => {
    const svg = toDiagramSvg(buildCircuitDiagram({
      title: 'Op amp SVG',
      type: 'opamp',
      supplyVoltage: 12,
      components: [
        { ref: 'XU1', kind: 'opamp', value: 'LM358', nodes: ['VINP', 'VINN', 'VOUT', 'VCC', '0'] },
        { ref: 'V1', kind: 'voltage_source', value: '12V', nodes: ['VCC', '0'] },
      ],
      notes: [],
    }));

    expect(svg).toContain('<polygon class="diagram-fill"');
    expect(svg).toContain('>+</text>');
    expect(svg).toContain('>-</text>');
    expect(svg).toContain('>V+</text>');
    expect(svg).toContain('>V-</text>');
  });

  it('warns when an op amp is missing schematic role nodes', () => {
    const validation = validateCircuit({
      title: 'Incomplete op amp',
      type: 'opamp',
      supplyVoltage: 5,
      components: [
        { ref: 'XU1', kind: 'opamp', value: 'LM358', nodes: ['VINP', 'VINN', 'VOUT'] },
        { ref: 'V1', kind: 'voltage_source', value: '5V', nodes: ['VCC', '0'] },
      ],
      notes: [],
    });

    expect(validation.ok).toBe(true);
    expect(validation.warnings).toContain('XU1 op amp should include + input, - input, output, V+, and V- nodes.');
  });

  it('keeps diagram net memberships consistent with the KiCad netlist', () => {
    const diagramMembership = netMembershipFromDiagram(buildCircuitDiagram(aiCircuit));
    const kicadMembership = netMembershipFromKiCad(toKiCadNetlist(aiCircuit));

    expect([...diagramMembership.keys()].sort()).toEqual([...kicadMembership.keys()].sort());
    for (const [net, connections] of kicadMembership.entries()) {
      expect(diagramMembership.get(net)).toEqual(connections);
    }
  });

  it('exports the generated diagram model as SVG', () => {
    const diagram = buildCircuitDiagram(aiCircuit);
    const svg = toDiagramSvg(diagram);

    expect(svg).toContain('<svg');
    expect(svg).toContain('R1');
    expect(svg).toContain('C1');
    // Fully routed with physical wires, not labeled-net stubs.
    expect(diagram.netLabels).toHaveLength(0);
    // Slot placement pins parts to fixed cells, so wires may cross and bridge —
    // bridges/junctions are valid routing artifacts here, just well-formed arrays.
    expect(Array.isArray(diagram.bridges)).toBe(true);
    expect(Array.isArray(diagram.junctions)).toBe(true);
    expect(diagram.slotLayout).toBeTruthy();
  });

  it('exports schematic ports in the generated diagram SVG', () => {
    const diagram = buildCircuitDiagram({
      ...aiCircuit,
      schematic: {
        version: 1,
        topology: 'low_pass',
        externalTerminals: [
          { net: 'VIN', label: 'VIN', type: 'input', side: 'left', explicit: true },
          { net: 'VOUT', label: 'VOUT', type: 'output', side: 'right', explicit: true },
        ],
        netRoles: [
          { net: 'VIN', role: 'input', side: 'left' },
          { net: 'VOUT', role: 'output', side: 'right' },
        ],
      },
    });
    const svg = toDiagramSvg(diagram);

    expect(diagram.ports.map((port) => port.net).sort()).toEqual(['VIN', 'VOUT']);
    expect(svg).toContain('class="diagram-port"');
    expect(svg).toContain('VIN');
    expect(svg).toContain('VOUT');
  });

  it('routes a generated difference amplifier with physical wires instead of labeled nets', () => {
    expect(() => layoutCircuitDiagram(differenceAmplifier)).not.toThrow();
    const diagram = buildCircuitDiagram(differenceAmplifier);
    const spice = toSpice(differenceAmplifier);
    const kicadNetlist = toKiCadNetlist(differenceAmplifier);
    const connectedPins = differenceAmplifier.components.reduce((count, component) =>
      count + component.nodes.filter((node, index) =>
        node !== `NC_${component.ref}_${index + 1}` && node !== `${component.ref}_${index + 1}`).length, 0);

    expect(diagram.layoutMode).toBeUndefined();
    expect(diagram.layoutWarning).toBeUndefined();
    expect(diagram.components.map((part) => part.ref)).toEqual(
      differenceAmplifier.components.map((part) => part.ref),
    );
    expect(diagram.wires).toHaveLength(connectedPins);
    expect(diagram.netLabels).toHaveLength(0);
    expect(diagram.wires.every((wire) => wire.points.length >= 2 && !wire.labelId)).toBe(true);
    ['VBIAS', 'OPP', 'OPN', 'VCC', 'VOUT', '0'].forEach((node) => expectNodePhysicallyConnected(diagram, node));
    expect(spice).toContain('XU1 OPP OPN VOUT VCC 0 LM358');
    expect(spice).toContain('R2 OPP VBIAS 10k');
    expect(kicadNetlist).toContain('<net');
    expect(kicadNetlist).toContain('name="VBIAS"');
  });
});

describe('microcontroller boards', () => {
  const esp32Circuit = {
    title: 'ESP32 LED',
    type: 'mcu_led',
    supplyVoltage: 3.3,
    components: [
      {
        ref: 'U1',
        kind: 'esp32',
        value: 'DevKit V1',
        nodes: ['VCC3', '0', 'NC_U1_3', 'NC_U1_4', 'LED', 'NC_U1_6', 'NC_U1_7', 'NC_U1_8', 'NC_U1_9', 'NC_U1_10', 'NC_U1_11', 'NC_U1_12'],
      },
      { ref: 'RLED', kind: 'resistor', value: '220', nodes: ['LED', 'LEDK'] },
      { ref: 'DLED1', kind: 'led', value: 'blue', nodes: ['LEDK', '0'] },
      { ref: 'R2', kind: 'resistor', value: '10k', nodes: ['VCC3', '0'] },
    ],
    notes: [],
  };

  it('exports MCUs as SPICE comments, never element lines', () => {
    const spice = toSpice(esp32Circuit);
    expect(spice).toContain('* U1 esp32 (microcontroller board, not simulated)');
    expect(spice.split('\n').some((line) => /^U1\s/i.test(line))).toBe(false);
    expect(spice).toContain('RLED LED LEDK 220');
    expect(spice).toContain('.end');
  });

  it('does not flag NC placeholder pins as floating nets', () => {
    const validation = validateCircuit(esp32Circuit);
    expect(validation.ok).toBe(true);
    expect(validation.warnings.filter((warning) => warning.includes('NC_U1'))).toHaveLength(0);
  });

  it('warns when an MCU pin list has the wrong length', () => {
    const truncated = {
      ...esp32Circuit,
      components: [
        { ...esp32Circuit.components[0], nodes: ['VCC3', '0', 'LED'] },
        ...esp32Circuit.components.slice(1),
      ],
    };
    const validation = validateCircuit(truncated);
    expect(validation.warnings.some((warning) => warning.includes('exactly 12 nodes'))).toBe(true);
  });

  it('lays out MCU circuits on the canvas without errors', () => {
    const diagram = buildCircuitDiagram(esp32Circuit);
    const mcu = diagram.components.find((part) => part.ref === 'U1');
    expect(mcu.symbolType).toBe('mcu');
    expect(mcu.pins).toHaveLength(12);
  });
});
