// Hand-authored surface-mount footprints.
//
// kicadFootprintLibrary.js is generated by scripts/extract-kicad-footprints.mjs
// from a KiCad install and must not be edited; these records live here instead.
// Geometry follows the KiCad 6 originals named in each libId (pad size, pitch
// and courtyard), authored by hand rather than extracted — close enough to
// fabricate, not byte-identical to the upstream library.
//
// Same record shape as the generated library (mm, y-down, recentered on the
// courtyard midpoint), plus two fields the through-hole records never carry:
//
//   type   'smd' — the pad is copper on one side only, with no barrel
//   layer  'top' | 'bottom' — which side that copper is on
//
// A pad with no `type` is through-hole and lives on both layers, which is what
// every generated record is. `drill: 0` marks the absence of a hole; the DRC
// already skips its annular-ring check when drill is falsy.

/** Two-pad chip package (0603/0805/1206), pads mirrored about the origin. */
const chip = (libId, { pitch, padW, padH, courtX, courtY }) => ({
  libId,
  pads: [1, 2].map((number, index) => ({
    number: String(number),
    x: index === 0 ? -pitch / 2 : pitch / 2,
    y: 0,
    shape: 'rect',
    size: { w: padW, h: padH },
    drill: 0,
    angle: 0,
    type: 'smd',
    layer: 'top',
  })),
  silk: [
    { type: 'line', start: { x: -courtX, y: -courtY }, end: { x: courtX, y: -courtY }, width: 0.12 },
    { type: 'line', start: { x: -courtX, y: courtY }, end: { x: courtX, y: courtY }, width: 0.12 },
  ],
  fab: [],
  courtyard: { minX: -courtX, minY: -courtY, maxX: courtX, maxY: courtY },
});

/** Dual-row gull-wing package (SOIC/TSSOP): pins down one side then back up the other. */
const dualRow = (libId, { count, pitch, rowSpan, padW, padH, courtX, courtY }) => {
  const perSide = count / 2;
  const first = -((perSide - 1) / 2) * pitch;
  return {
    libId,
    pads: Array.from({ length: count }, (_, index) => {
      const left = index < perSide;
      const along = left ? index : count - 1 - index;
      return {
        number: String(index + 1),
        x: left ? -rowSpan / 2 : rowSpan / 2,
        y: first + along * pitch,
        shape: 'rect',
        size: { w: padW, h: padH },
        drill: 0,
        angle: 0,
        type: 'smd',
        layer: 'top',
      };
    }),
    silk: [
      { type: 'line', start: { x: -courtX + 0.3, y: -courtY + 0.2 }, end: { x: courtX - 0.3, y: -courtY + 0.2 }, width: 0.12 },
      { type: 'line', start: { x: -courtX + 0.3, y: courtY - 0.2 }, end: { x: courtX - 0.3, y: courtY - 0.2 }, width: 0.12 },
      // Pin-1 dot, outboard of pad 1.
      { type: 'circle', center: { x: -rowSpan / 2 - 0.5, y: first }, radius: 0.15, width: 0.12 },
    ],
    fab: [],
    courtyard: { minX: -courtX, minY: -courtY, maxX: courtX, maxY: courtY },
  };
};

/**
 * Castellated RF module: perimeter pads on three edges (left top->bottom,
 * bottom left->right, right bottom->top — the counter-clockwise numbering
 * Espressif uses), an exposed thermal pad, and an antenna keep-out across the
 * top edge (no pads, hatched on silk). Geometry follows the KiCad 6
 * RF_Module originals but is authored with every pitch-axis coordinate a
 * multiple of the 0.635 mm routing grid (a pure origin shift from the KiCad
 * frame), so grid-snapped placement puts a routing cell dead-centre in every
 * pad and escapes never neck below the widest rung.
 */
const castellatedModule = (libId, {
  sideCount, bottomCount, pitch, rowSpan, sideFirstY, bottomY, padLong, padShort,
  epad, body, antennaY, courtyard,
}) => {
  // Accumulated pitch steps pick up float noise (-5.08 + 13*1.27 =
  // 11.430000000000001); round so coordinates stay exact in tests and exports.
  const round = (value) => Math.round(value * 1e6) / 1e6;
  const pad = (number, x, y, w, h) => ({
    number: String(number), x: round(x), y: round(y), shape: 'rect', size: { w, h },
    drill: 0, angle: 0, type: 'smd', layer: 'top',
  });
  const pads = [];
  for (let i = 0; i < sideCount; i += 1) {
    pads.push(pad(i + 1, -rowSpan / 2, sideFirstY + i * pitch, padLong, padShort));
  }
  const bottomFirstX = -((bottomCount - 1) / 2) * pitch;
  for (let i = 0; i < bottomCount; i += 1) {
    pads.push(pad(sideCount + 1 + i, bottomFirstX + i * pitch, bottomY, padShort, padLong));
  }
  for (let i = 0; i < sideCount; i += 1) {
    pads.push(pad(sideCount + bottomCount + 1 + i, rowSpan / 2, sideFirstY + (sideCount - 1 - i) * pitch, padLong, padShort));
  }
  pads.push(pad(pads.length + 1, epad.x, epad.y, epad.w, epad.h));

  const line = (x1, y1, x2, y2) => ({ type: 'line', start: { x: x1, y: y1 }, end: { x: x2, y: y2 }, width: 0.12 });
  const bodyRect = [
    line(body.minX, body.minY, body.maxX, body.minY),
    line(body.maxX, body.minY, body.maxX, body.maxY),
    line(body.maxX, body.maxY, body.minX, body.maxY),
    line(body.minX, body.maxY, body.minX, body.minY),
  ];
  // Antenna boundary stops short of the pad columns; the hatch marks the
  // keep-out zone the way module silkscreens usually do.
  const hatchSpan = (antennaY - body.minY) / 4;
  const silk = [
    ...bodyRect,
    line(body.minX + 1.2, antennaY, body.maxX - 1.2, antennaY),
    ...[1, 2, 3].map((i) => line(
      body.minX + 2 + (i - 1) * 5, antennaY - hatchSpan,
      body.minX + 2 + (i - 1) * 5 + hatchSpan * 2, antennaY - hatchSpan * 3,
    )),
    // Pin-1 dot, outboard of pad 1.
    { type: 'circle', center: { x: -rowSpan / 2 - 1.1, y: sideFirstY }, radius: 0.15, width: 0.12 },
  ];
  const fab = [...bodyRect, line(body.minX, antennaY, body.maxX, antennaY)];
  return { libId, pads, silk, fab, courtyard };
};

export const SMD_FOOTPRINTS = {
  // Metric 2012 / imperial 0805 — the default hand-solderable chip size.
  'Resistor_SMD:R_0805_2012Metric': chip('Resistor_SMD:R_0805_2012Metric',
    { pitch: 1.875, padW: 1.025, padH: 1.4, courtX: 1.68, courtY: 0.95 }),
  'Capacitor_SMD:C_0805_2012Metric': chip('Capacitor_SMD:C_0805_2012Metric',
    { pitch: 1.875, padW: 1.025, padH: 1.4, courtX: 1.7, courtY: 0.98 }),
  // Metric 1608 / imperial 0603 — denser, still hand-solderable.
  'Resistor_SMD:R_0603_1608Metric': chip('Resistor_SMD:R_0603_1608Metric',
    { pitch: 1.5, padW: 0.9, padH: 0.95, courtX: 1.48, courtY: 0.73 }),
  'Capacitor_SMD:C_0603_1608Metric': chip('Capacitor_SMD:C_0603_1608Metric',
    { pitch: 1.5, padW: 0.9, padH: 0.95, courtX: 1.48, courtY: 0.73 }),
  // 1206 — the large chip size, used for higher-power resistors.
  'Resistor_SMD:R_1206_3216Metric': chip('Resistor_SMD:R_1206_3216Metric',
    { pitch: 2.8, padW: 1.15, padH: 1.8, courtX: 2.2, courtY: 1.15 }),

  // LED in a 0805 body: pad 1 is the cathode in the KiCad original, matching
  // the through-hole LED record's polarity convention.
  'LED_SMD:LED_0805_2012Metric': chip('LED_SMD:LED_0805_2012Metric',
    { pitch: 1.875, padW: 1.025, padH: 1.4, courtX: 1.68, courtY: 0.95 }),

  // SOT-23: two pads on one side, one opposite. Pin order matches the KiCad
  // original (1 and 2 on the two-pad side, 3 alone).
  'Package_TO_SOT_SMD:SOT-23': {
    libId: 'Package_TO_SOT_SMD:SOT-23',
    pads: [
      { number: '1', x: -0.9375, y: 1.04, shape: 'rect', size: { w: 0.9, h: 1.0 }, drill: 0, angle: 0, type: 'smd', layer: 'top' },
      { number: '2', x: 0.9375, y: 1.04, shape: 'rect', size: { w: 0.9, h: 1.0 }, drill: 0, angle: 0, type: 'smd', layer: 'top' },
      { number: '3', x: 0, y: -1.04, shape: 'rect', size: { w: 0.9, h: 1.0 }, drill: 0, angle: 0, type: 'smd', layer: 'top' },
    ],
    silk: [
      { type: 'line', start: { x: -1.6, y: -0.5 }, end: { x: 1.6, y: -0.5 }, width: 0.12 },
      { type: 'line', start: { x: -1.6, y: 0.5 }, end: { x: 1.6, y: 0.5 }, width: 0.12 },
    ],
    fab: [],
    courtyard: { minX: -1.92, minY: -1.85, maxX: 1.92, maxY: 1.85 },
  },

  // ESP32-S3-WROOM-1: 18 x 25.5 mm castellated module, 40 perimeter pads at
  // 1.27 mm pitch (left 1-14 top->bottom, bottom 15-26 left->right, right
  // 27-40 bottom->up, CCW from the top-left as the datasheet numbers them)
  // plus the 3.9 mm exposed thermal pad as pad 41. The top ~7.5 mm of the
  // body is the PCB antenna keep-out — no pads, hatched on silk. The paste
  // layer emits the EPAD as one solid 3.9 mm aperture; a production stencil
  // would window-pane it to ~65% coverage — accepted v1 limitation.
  'RF_Module:ESP32-S3-WROOM-1': castellatedModule('RF_Module:ESP32-S3-WROOM-1', {
    sideCount: 14, bottomCount: 12, pitch: 1.27, rowSpan: 17.5,
    sideFirstY: -5.08, bottomY: 12.68, padLong: 1.5, padShort: 0.9,
    epad: { x: 0, y: 3.175, w: 3.9, h: 3.9 },
    body: { minX: -9, minY: -12.57, maxX: 9, maxY: 12.93 },
    antennaY: -5.6,
    courtyard: { minX: -10.1, minY: -12.82, maxX: 9.75, maxY: 13.68 },
  }),

  // SOIC-8, 1.27 mm pitch — the surface-mount counterpart of DIP-8.
  'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm': dualRow('Package_SO:SOIC-8_3.9x4.9mm_P1.27mm',
    { count: 8, pitch: 1.27, rowSpan: 4.95, padW: 1.95, padH: 0.6, courtX: 3.7, courtY: 2.75 }),
  'Package_SO:SOIC-14_3.9x8.65mm_P1.27mm': dualRow('Package_SO:SOIC-14_3.9x8.65mm_P1.27mm',
    { count: 14, pitch: 1.27, rowSpan: 4.95, padW: 1.95, padH: 0.6, courtX: 3.7, courtY: 4.6 }),
  'Package_SO:SOIC-16_3.9x9.9mm_P1.27mm': dualRow('Package_SO:SOIC-16_3.9x9.9mm_P1.27mm',
    { count: 16, pitch: 1.27, rowSpan: 4.95, padW: 1.95, padH: 0.6, courtX: 3.7, courtY: 5.25 }),
};

/** True when a footprint record places any copper on one side only. */
export const isSurfaceMount = (record) => (record?.pads || []).some((pad) => pad.type === 'smd');
