// Hand-authored surface-mount footprints.
//
// kicadFootprintLibrary.js is generated by scripts/extract-kicad-footprints.mjs
// from a KiCad install and must not be edited; these records live here instead.
// Geometry follows the KiCad 6 originals named in each libId (pad size, pitch
// and courtyard), authored by hand rather than extracted — close enough to
// fabricate, not byte-identical to the upstream library.
//
// Same record shape as the generated library (mm, y-down, recentered on the
// courtyard midpoint), plus two fields the through-hole records never carry:
//
//   type   'smd' — the pad is copper on one side only, with no barrel
//   layer  'top' | 'bottom' — which side that copper is on
//
// A pad with no `type` is through-hole and lives on both layers, which is what
// every generated record is. `drill: 0` marks the absence of a hole; the DRC
// already skips its annular-ring check when drill is falsy.

/** Two-pad chip package (0603/0805/1206), pads mirrored about the origin. */
const chip = (libId, { pitch, padW, padH, courtX, courtY }) => ({
  libId,
  pads: [1, 2].map((number, index) => ({
    number: String(number),
    x: index === 0 ? -pitch / 2 : pitch / 2,
    y: 0,
    shape: 'rect',
    size: { w: padW, h: padH },
    drill: 0,
    angle: 0,
    type: 'smd',
    layer: 'top',
  })),
  silk: [
    { type: 'line', start: { x: -courtX, y: -courtY }, end: { x: courtX, y: -courtY }, width: 0.12 },
    { type: 'line', start: { x: -courtX, y: courtY }, end: { x: courtX, y: courtY }, width: 0.12 },
  ],
  fab: [],
  courtyard: { minX: -courtX, minY: -courtY, maxX: courtX, maxY: courtY },
});

/** Dual-row gull-wing package (SOIC/TSSOP): pins down one side then back up the other. */
const dualRow = (libId, { count, pitch, rowSpan, padW, padH, courtX, courtY }) => {
  const perSide = count / 2;
  const first = -((perSide - 1) / 2) * pitch;
  return {
    libId,
    pads: Array.from({ length: count }, (_, index) => {
      const left = index < perSide;
      const along = left ? index : count - 1 - index;
      return {
        number: String(index + 1),
        x: left ? -rowSpan / 2 : rowSpan / 2,
        y: first + along * pitch,
        shape: 'rect',
        size: { w: padW, h: padH },
        drill: 0,
        angle: 0,
        type: 'smd',
        layer: 'top',
      };
    }),
    silk: [
      { type: 'line', start: { x: -courtX + 0.3, y: -courtY + 0.2 }, end: { x: courtX - 0.3, y: -courtY + 0.2 }, width: 0.12 },
      { type: 'line', start: { x: -courtX + 0.3, y: courtY - 0.2 }, end: { x: courtX - 0.3, y: courtY - 0.2 }, width: 0.12 },
      // Pin-1 dot, outboard of pad 1.
      { type: 'circle', center: { x: -rowSpan / 2 - 0.5, y: first }, radius: 0.15, width: 0.12 },
    ],
    fab: [],
    courtyard: { minX: -courtX, minY: -courtY, maxX: courtX, maxY: courtY },
  };
};

export const SMD_FOOTPRINTS = {
  // Metric 2012 / imperial 0805 — the default hand-solderable chip size.
  'Resistor_SMD:R_0805_2012Metric': chip('Resistor_SMD:R_0805_2012Metric',
    { pitch: 1.875, padW: 1.025, padH: 1.4, courtX: 1.68, courtY: 0.95 }),
  'Capacitor_SMD:C_0805_2012Metric': chip('Capacitor_SMD:C_0805_2012Metric',
    { pitch: 1.875, padW: 1.025, padH: 1.4, courtX: 1.7, courtY: 0.98 }),
  // Metric 1608 / imperial 0603 — denser, still hand-solderable.
  'Resistor_SMD:R_0603_1608Metric': chip('Resistor_SMD:R_0603_1608Metric',
    { pitch: 1.5, padW: 0.9, padH: 0.95, courtX: 1.48, courtY: 0.73 }),
  'Capacitor_SMD:C_0603_1608Metric': chip('Capacitor_SMD:C_0603_1608Metric',
    { pitch: 1.5, padW: 0.9, padH: 0.95, courtX: 1.48, courtY: 0.73 }),
  // 1206 — the large chip size, used for higher-power resistors.
  'Resistor_SMD:R_1206_3216Metric': chip('Resistor_SMD:R_1206_3216Metric',
    { pitch: 2.8, padW: 1.15, padH: 1.8, courtX: 2.2, courtY: 1.15 }),

  // LED in a 0805 body: pad 1 is the cathode in the KiCad original, matching
  // the through-hole LED record's polarity convention.
  'LED_SMD:LED_0805_2012Metric': chip('LED_SMD:LED_0805_2012Metric',
    { pitch: 1.875, padW: 1.025, padH: 1.4, courtX: 1.68, courtY: 0.95 }),

  // SOT-23: two pads on one side, one opposite. Pin order matches the KiCad
  // original (1 and 2 on the two-pad side, 3 alone).
  'Package_TO_SOT_SMD:SOT-23': {
    libId: 'Package_TO_SOT_SMD:SOT-23',
    pads: [
      { number: '1', x: -0.9375, y: 1.04, shape: 'rect', size: { w: 0.9, h: 1.0 }, drill: 0, angle: 0, type: 'smd', layer: 'top' },
      { number: '2', x: 0.9375, y: 1.04, shape: 'rect', size: { w: 0.9, h: 1.0 }, drill: 0, angle: 0, type: 'smd', layer: 'top' },
      { number: '3', x: 0, y: -1.04, shape: 'rect', size: { w: 0.9, h: 1.0 }, drill: 0, angle: 0, type: 'smd', layer: 'top' },
    ],
    silk: [
      { type: 'line', start: { x: -1.6, y: -0.5 }, end: { x: 1.6, y: -0.5 }, width: 0.12 },
      { type: 'line', start: { x: -1.6, y: 0.5 }, end: { x: 1.6, y: 0.5 }, width: 0.12 },
    ],
    fab: [],
    courtyard: { minX: -1.92, minY: -1.85, maxX: 1.92, maxY: 1.85 },
  },

  // SOIC-8, 1.27 mm pitch — the surface-mount counterpart of DIP-8.
  'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm': dualRow('Package_SO:SOIC-8_3.9x4.9mm_P1.27mm',
    { count: 8, pitch: 1.27, rowSpan: 4.95, padW: 1.95, padH: 0.6, courtX: 3.7, courtY: 2.75 }),
  'Package_SO:SOIC-14_3.9x8.65mm_P1.27mm': dualRow('Package_SO:SOIC-14_3.9x8.65mm_P1.27mm',
    { count: 14, pitch: 1.27, rowSpan: 4.95, padW: 1.95, padH: 0.6, courtX: 3.7, courtY: 4.6 }),
  'Package_SO:SOIC-16_3.9x9.9mm_P1.27mm': dualRow('Package_SO:SOIC-16_3.9x9.9mm_P1.27mm',
    { count: 16, pitch: 1.27, rowSpan: 4.95, padW: 1.95, padH: 0.6, courtX: 3.7, courtY: 5.25 }),
};

/** True when a footprint record places any copper on one side only. */
export const isSurfaceMount = (record) => (record?.pads || []).some((pad) => pad.type === 'smd');
